"""empty message

Revision ID: 18999d59fa65
Revises: 3e9fd5679e05
Create Date: 2022-12-08 14:57:17.077995

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18999d59fa65'
down_revision = '3e9fd5679e05'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('losses', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('losses')

    # ### end Alembic commands ###
