"""empty message

Revision ID: 3e9fd5679e05
Revises: a9a3b17fc5ac
Create Date: 2022-12-08 14:25:00.084664

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e9fd5679e05'
down_revision = 'a9a3b17fc5ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('wins', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('wins')

    # ### end Alembic commands ###
